from owlready2 import *

from ontoConstants import *

instanceIndicator = 'Instance'

# Initially hardcoding the structure of some links in the ontology just to test this system out on Items/Actions/etc.
# Some of these may not be quite 'necessary' - e.g. Affordances for items.
importantNodeSets = {ITEM_NODE: [ITEM_ROLE_NODE, AFFORDANCE_NODE, ITEM_DESCRIPTION_NODE],
                     ACTION_NODE: [ITEM_NODE, TRANSITION_DESCRIPTION_NODE],
                     ITEM_DESCRIPTION_NODE: [ITEM_LOCATION_NODE, ITEM_COLOR_NODE, ITEM_SHAPE_NODE, ITEM_TYPE_NODE]}

autoGeneratedNodeSets = {}
autoGeneratedNodeEdgeSets = {}

def generateNodeSets():
    # Get the uninitalized ontology
    emptyGraph = get_ontology("http://localhost:3030/uagent").load()
    # Iterate through all of the classes in the ontology
    for ontoClass in emptyGraph.classes():
        linkedNodes = []
        edgesAndNodes = []
        # Iterate through all of the properties applied to the given class
        for property in ontoClass.get_class_properties():
            # Get the list of "targets" for the property
            propertyTargetList = property[ontoClass]
            # For each target, check if it's an ontology item as opposed to a string or boolean
            for propertyTarget in propertyTargetList:
                if isinstance(propertyTarget, ThingClass):
                    # Append just the target to the list of target nodes
                    linkedNodes.append(propertyTarget.name)
                    # Append both the name of the property and the target to the edge/node list
                    edgesAndNodes. append((property.name, propertyTarget.name))
                    #print(property[ontoClass])

        # Update the dictionaries for just nodes and node/edge combos
        if len(linkedNodes) > 0:
            autoGeneratedNodeSets.update({ontoClass.name: linkedNodes})
            autoGeneratedNodeEdgeSets.update({ontoClass.name: edgesAndNodes})

    #print(autoGeneratedNodeSets)
    #print(autoGeneratedNodeEdgeSets)


def checkInitializedGraphEdges(onto):
    # testGraph = networkx.MultiDiGraph()
    # testImport(testGraph)
    #for currentType in importantNodeSets:
    for currentType in autoGeneratedNodeEdgeSets:
        #print('\n')
        #print("Expected nodes to be connected to " + currentType + " nodes:")
        #print(autoGeneratedNodeSets.get(currentType))
        #print('\n')
        with onto:
            # Print list of instances of this item type
            #print(onto[currentType].instances())
            # Iterate through all instances of the currently selected type
            for currentInstance in onto[currentType].instances():
                nodeFullyConnected = True
                listOfMissingEdgesAndNodes = []
                for expectedEdge, expectedNode in autoGeneratedNodeEdgeSets.get(currentType):
                    # Check if the expected node has a relationship to the current instance
                    foundConnectedNode = checkForRelationEdges(currentInstance, expectedEdge, expectedNode)
                    # If the expected node is not found, then flag the node as not fully connected and track missing
                    # nodes
                    if foundConnectedNode == False:
                        nodeFullyConnected = False
                        listOfMissingEdgesAndNodes.append((expectedEdge, expectedNode))
                # If the node is fully connected, it's good
                # If the node is not fully connected, then flag it to the user and inform them of what's missing
                if nodeFullyConnected == True:
                    #print(str(currentInstance) + " fully connected.")
                    pass
                else:
                    print("WARNING: " + str(currentInstance) + " not fully connected.  Expected edges/nodes not found: "
                          + str(listOfMissingEdgesAndNodes))

    print('\n')


def checkForRelationEdges(currentInstance, expectedEdge, expectedNode):
    nodeFound = False
    # Get all of the outgoing properties for the instance
    for prop in currentInstance.get_properties():
        # Get the target of the outgoing property
        for propValue in prop[currentInstance]:
            # Check if the property contains the expected node as the target
            #nodeFound = re.search(expectedNode.lower() + r'\d+', str(propValue))
            nodeType = type(propValue)
            if isinstance(nodeType, ThingClass):
                if nodeType.name == expectedNode:
                    if prop.name == expectedEdge:
                        nodeFound = True
                else:
                    # Check if it's a subtype of the expected node type?
                    for isA in nodeType.ancestors():
                        if isA.name == expectedNode:
                            if prop.name == expectedEdge:
                                return True
                        else:
                            nodeFound = False
            else:
                nodeFound = False
            # If so, return true and print the property
            if nodeFound:
                # print(currentInstance, prop.python_name, propValue)
                return True
    # Get all of the incoming properties for the instance
    for inverseProp in currentInstance.get_inverse_properties():
        nodeFound = False
        # Get the source and value of the property
        source, value = inverseProp
        # Check if the property contains the expected node as the source
        # nodeFound = re.search(expectedNode.lower() + r'\d+', str(source))
        nodeType = type(source)
        if isinstance(nodeType, ThingClass):
            if nodeType.name == expectedNode:
                if inverseProp.name == expectedEdge:
                    nodeFound = True
            else:
                # Check if it's a subtype of the expected node type?
                for isA in nodeType.ancestors():
                    if isA.name == expectedNode:
                        if inverseProp.name == expectedEdge:
                            return True
                    else:
                        nodeFound = False
        else:
            nodeFound = False
        # If so, return true and print the property
        if nodeFound:
            # print(currentInstance, prop.python_name, propValue)
            return True
    # If nothing found, return False
    return False



def checkInitializedGraphNoEdges(onto):
    # testGraph = networkx.MultiDiGraph()
    # testImport(testGraph)
    #for currentType in importantNodeSets:
    for currentType in autoGeneratedNodeSets:
        print('\n')
        print("Expected nodes to be connected to " + currentType + " nodes:")
        print(autoGeneratedNodeSets.get(currentType))
        print('\n')
        with onto:
            # Print list of instances of this item type
            print(onto[currentType].instances())
            # Iterate through all instances of the currently selected type
            for currentInstance in onto[currentType].instances():
                nodeFullyConnected = True
                listOfMissingNodes = []
                for expectedNode in autoGeneratedNodeSets.get(currentType):
                    # Check if the expected node has a relationship to the current instance
                    foundConnectedNode = checkForRelationNoEdges(currentInstance, expectedNode)
                    # If the expected node is note found, then flag the node as not fully connected and track missing
                    # nodes
                    if foundConnectedNode == False:
                        nodeFullyConnected = False
                        listOfMissingNodes.append(expectedNode)
                # If the node is fully connected, it's good
                # If the node is not fully connected, then flag it to the user and inform them of what's missing
                if nodeFullyConnected == True:
                    print(str(currentInstance) + " fully connected.")
                else:
                    print("WARNING: " + str(currentInstance) + " not fully connected.  Expected nodes not found: "
                          + str(listOfMissingNodes))

    print('\n')


def checkForRelationNoEdges(currentInstance, expectedNode):
    nodeFound = False
    # Get all of the outgoing properties for the instance
    for prop in currentInstance.get_properties():
        # Get the target of the outgoing property
        for propValue in prop[currentInstance]:
            # Check if the property contains the expected node as the target
            #nodeFound = re.search(expectedNode.lower() + r'\d+', str(propValue))
            nodeType = type(propValue)
            if isinstance(nodeType, ThingClass):
                if nodeType.name == expectedNode:
                    nodeFound = True
                else:
                    # Check if it's a subtype of the expected node type?
                    for isA in nodeType.ancestors():
                        if isA.name == expectedNode:
                            return True
                        else:
                            nodeFound = False
            else:
                nodeFound = False
            # If so, return true and print the property
            if nodeFound:
                # print(currentInstance, prop.python_name, propValue)
                return True
    # Get all of the incoming properties for the instance
    for inverseProp in currentInstance.get_inverse_properties():
        # Get the source and value of the property
        source, value = inverseProp
        # Check if the property contains the expected node as the source
        nodeFound = re.search(expectedNode.lower() + r'\d+', str(source))
        nodeType = type(propValue)
        if isinstance(nodeType, ThingClass):
            if nodeType.name == expectedNode:
                nodeFound = True
            else:
                nodeFound = False
        else:
            nodeFound = False
        # If so, return true and print the property
        if nodeFound:
            # print(currentInstance, prop.python_name, propValue)
            return True
    # If nothing found, return False
    return False


#generateNodeSets()
#checkInitializedGraphEdges()
