import re
import networkx
from SPARQLWrapper import SPARQLWrapper, JSON
from owlready2 import *

from ontoConstants import *

instanceIndicator = 'Instance'

# Initially hardcoding the structure of some links in the ontology just to test this system out on Items/Actions/etc.
# Some of these may not be quite 'necessary' - e.g. Affordances for items.
importantNodeSets = {ITEM_NODE: [ITEM_ROLE_NODE, AFFORDANCE_NODE, ITEM_DESCRIPTION_NODE],
                     ACTION_NODE: [ITEM_NODE, TRANSITION_DESCRIPTION_NODE],
                     ITEM_DESCRIPTION_NODE: [ITEM_LOCATION_NODE, ITEM_COLOR_NODE, ITEM_SHAPE_NODE, ITEM_TYPE_NODE]}

autoGeneratedNodeSets = {}


def generateNodeSets():
    emptyGraph = get_ontology("http://localhost:3030/uagent").load()
    for ontoClass in emptyGraph.classes():
        print(ontoClass)


def checkInitializedGraph():
    onto = get_ontology("http://localhost:3030/uagent-initialized").load()
    # testGraph = networkx.MultiDiGraph()
    # testImport(testGraph)
    for currentType in importantNodeSets:
        print('\n')
        print("Expected nodes to be connected to " + currentType + " nodes:")
        print(importantNodeSets.get(currentType))
        print('\n')
        with onto:
            # Print list of instances of this item type
            print(onto[currentType].instances())
            # Iterate through all instances of the currently selected type
            for currentInstance in onto[currentType].instances():
                nodeFullyConnected = True
                listOfMissingNodes = []
                for expectedNode in importantNodeSets.get(currentType):
                    # Check if the expected node has a relationship to the current instance
                    foundConnectedNode = checkForRelation(currentInstance, expectedNode)
                    # If the expected node is note found, then flag the node as not fully connected and track missing
                    # nodes
                    if foundConnectedNode == False:
                        nodeFullyConnected = False
                        listOfMissingNodes.append(expectedNode)
                # If the node is fully connected, it's good
                # If the node is not fully connected, then flag it to the user and inform them of what's missing
                if nodeFullyConnected == True:
                    print(str(currentInstance) + " fully connected.")
                else:
                    print("WARNING: " + str(currentInstance) + " not fully connected.  Expected nodes not found: "
                          + str(listOfMissingNodes))

    print('\n')


def checkForRelation(currentInstance, expectedNode):
    # Get all of the outgoing properties for the instance
    for prop in currentInstance.get_properties():
        # Get the target of the outgoing property
        for propValue in prop[currentInstance]:
            # Check if the property contains the expected node as the target
            nodeFound = re.search(expectedNode.lower() + r'\d+', str(propValue))
            # If so, return true and print the property
            if nodeFound:
                # print(currentInstance, prop.python_name, propValue)
                return True
    # Get all of the incoming properties for the instance
    for inverseProp in currentInstance.get_inverse_properties():
        # Get the source and value of the property
        source, value = inverseProp
        # Check if the property contains the expected node as the source
        nodeFound = re.search(expectedNode.lower() + r'\d+', str(source))
        # If so, return true and print the property
        if nodeFound:
            # print(source, value, currentInstance)
            return True
    # If nothing found, return False
    return False


#generateNodeSets()
checkInitializedGraph()
