import re
import networkx
from SPARQLWrapper import SPARQLWrapper, JSON
from owlready2 import *

from ontoConstants import *

instanceIndicator = 'Instance'

# Initially hardcoding the structure of some links in the ontology just to test this system out on Items/Actions/etc.
# Some of these may not be quite 'necessary' - e.g. Affordances for items.
importantNodeSets = {ITEM_NODE: [ITEM_ROLE_NODE, AFFORDANCE_NODE, ITEM_DESCRIPTION_NODE],
                     ACTION_NODE: [ITEM_NODE, TRANSITION_DESCRIPTION_NODE],
                     ITEM_DESCRIPTION_NODE: [ITEM_LOCATION_NODE, ITEM_COLOR_NODE, ITEM_SHAPE_NODE, ITEM_TYPE_NODE]}

autoGeneratedNodeSets = {}


def generateNodeSets():
    emptyGraph = get_ontology("http://localhost:3030/uagent").load()
    for ontoClass in emptyGraph.classes():

        #print(ontoClass)
        #print(ontoClass.get_class_properties())
        linkedNodes = []
        for property in ontoClass.get_class_properties():
            propertyTargetList = property[ontoClass]
            for propertyTarget in propertyTargetList:
                if isinstance(propertyTarget, ThingClass):
                    linkedNodes.append(propertyTarget.name)
                    #print(property[ontoClass])

        if len(linkedNodes) > 0:
            autoGeneratedNodeSets.update({ontoClass.name: linkedNodes})


    print(autoGeneratedNodeSets)
        #print(emptyGraph.get_children_of(ontoClass))
    #for prop in emptyGraph.properties():
        #print(prop)
        #print("Domain" + str(prop.domain) + '\n')
        #print("Range " + str(prop.range) + '\n')
            #print(list(prop.))
    #autoGeneratedNodeSets.update()


def checkInitializedGraph():
    onto = get_ontology("http://localhost:3030/uagent-initialized").load()
    # testGraph = networkx.MultiDiGraph()
    # testImport(testGraph)
    #for currentType in importantNodeSets:
    for currentType in autoGeneratedNodeSets:
        print('\n')
        print("Expected nodes to be connected to " + currentType + " nodes:")
        print(autoGeneratedNodeSets.get(currentType))
        print('\n')
        with onto:
            # Print list of instances of this item type
            print(onto[currentType].instances())
            # Iterate through all instances of the currently selected type
            for currentInstance in onto[currentType].instances():
                nodeFullyConnected = True
                listOfMissingNodes = []
                for expectedNode in autoGeneratedNodeSets.get(currentType):
                    # Check if the expected node has a relationship to the current instance
                    foundConnectedNode = checkForRelation(currentInstance, expectedNode)
                    # If the expected node is note found, then flag the node as not fully connected and track missing
                    # nodes
                    if foundConnectedNode == False:
                        nodeFullyConnected = False
                        listOfMissingNodes.append(expectedNode)
                # If the node is fully connected, it's good
                # If the node is not fully connected, then flag it to the user and inform them of what's missing
                if nodeFullyConnected == True:
                    print(str(currentInstance) + " fully connected.")
                else:
                    print("WARNING: " + str(currentInstance) + " not fully connected.  Expected nodes not found: "
                          + str(listOfMissingNodes))

    print('\n')


def checkForRelation(currentInstance, expectedNode):
    # Get all of the outgoing properties for the instance
    for prop in currentInstance.get_properties():
        # Get the target of the outgoing property
        for propValue in prop[currentInstance]:
            # Check if the property contains the expected node as the target
            #nodeFound = re.search(expectedNode.lower() + r'\d+', str(propValue))
            nodeType = type(propValue)
            if isinstance(nodeType, ThingClass):
                if nodeType.name == expectedNode:
                    nodeFound = True
                else:
                    nodeFound = False
            else:
                nodeFound = False
            # If so, return true and print the property
            if nodeFound:
                # print(currentInstance, prop.python_name, propValue)
                return True
    # Get all of the incoming properties for the instance
    for inverseProp in currentInstance.get_inverse_properties():
        # Get the source and value of the property
        source, value = inverseProp
        # Check if the property contains the expected node as the source
        nodeFound = re.search(expectedNode.lower() + r'\d+', str(source))
        nodeType = type(propValue)
        if isinstance(nodeType, ThingClass):
            if nodeType.name == expectedNode:
                nodeFound = True
            else:
                nodeFound = False
        else:
            nodeFound = False
        # If so, return true and print the property
        if nodeFound:
            # print(currentInstance, prop.python_name, propValue)
            return True
    # If nothing found, return False
    return False


generateNodeSets()
checkInitializedGraph()
