# NODE NAMES
ITEM_NODE = 'Item'
ITEM_DESCRIPTION_NODE = 'ItemDescription'
ITEM_ROLE_NODE = 'ItemRole'
AFFORDANCE_NODE = 'Affordance'
TASK_NODE = 'ISR-MATBTask'
ACTION_NODE = 'Action'
SITUATION_DESCRIPTION_NODE = 'SituationDescription'
TRANSITION_DESCRIPTION_NODE = 'TransitionDescription'
# The below are ItemX because, despite the graph seemingly indicating otherwise, the OWL file seems to show them as such
ITEM_LOCATION_NODE = "ItemLocation"
ITEM_COLOR_NODE = "ItemColor"
ITEM_SHAPE_NODE = "ItemShape"
ITEM_TYPE_NODE = "ItemType"

# EDGE NAMES
HAS_ITEM_NAME_EDGE = ':hasItemName'
ASSUMED_BY_EDGE = ':assumedBy'
AFFORDS_EDGE = ':affords'
OF_TYPE_EDGE = ':ofType'
OF_ITEM_EDGE = ':ofItem'
IS_PRESENT_EDGE = ':isPresent'
REFERS_TO_ITEM_TYPE_EDGE = ':refersToItemType'
REFERS_TO_ITEM_SHAPE_EDGE = ':refersToItemShape'
REFERS_TO_ITEM_COLOR_EDGE = ':refersToItemColor'
REFERS_TO_ITEM_LOCATION_EDGE = ':refersToItemLocation'
HAS_EARLIER_CONDITION_EDGE = ':hasEarlierCondition'
HAS_CURRENT_CONDITION_EDGE = ':hasCurrentCondition'
PROVIDES_ROLE_EDGE = ':providesRole'
REFERS_TO_EDGE = ':refersTo'
TRIGGERS_EDGE = ':triggers'
HAS_PRE_SITUATION_DESCRIPTION_EDGE = ':hasPreSituationDescription'
HAS_POST_SITUATION_DESCRIPTION_EDGE = ':hasPostSituationDescription'
TYPE_EDGE = 'rdf:type'
HAS_NAME_EDGE = ':hasName'
